version: '3.4'

services:
### Mongo Db ###
  etendermongodb:
    container_name: etendermongodb
    restart: always
    ports:
      - "27017:27017"

### Product Service ###
  etender.products:
    container_name: etenderproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://etendermongodb:27017"
    depends_on:
      - etendermongodb
    ports:
      - "8000:80"
      
### Sourcing Service ###
  etender.sourcing:
    container_name: etendersourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://etendermongodb:27017"
    depends_on:
      - etendermongodb
    ports:
      - "8001:80"