version: '3.4'

services:
### Mongo Db ###
  etendermongodb:
    container_name: etendermongodb
    restart: always
    ports:
      - "27017:27017"

### RabbitMQ ###
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      
### MSSQL ###
  etendermssql:
    container_name: etendermssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"
      
### API Gateway ###
  etender.apigateway:
    container_name: etenderapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - etender.products
      - etender.sourcing
      - etender.order
    ports:
      - "5000:80"

### Product Service ###
  etender.products:
    container_name: etenderproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://etendermongodb:27017"
    depends_on:
      - etendermongodb
    ports:
      - "8000:80"
      
### Sourcing Service ###
  etender.sourcing:
    container_name: etendersourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://etendermongodb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - etendermongodb
      - rabbitmq
    ports:
      - "8001:80"
      
### Order Service ###
  etender.order:
    container_name: etenderorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=etendermssql;Database=OrderDb;User Id=sa;Password=Odb12345678"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - etendermssql
      - rabbitmq
    ports:
      - "8002:80"