version: '3.4'

services:
### Mongo Db ###
  etendermongodb:
    container_name: etendermongodb
    restart: always
    ports:
      - "27017:27017"

### RabbitMQ ###
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      
### MSSQL ###
  etendermssql:
    container_name: etendersqldb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"

### Product Service ###
  etender.products:
    container_name: etenderproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://etendermongodb:27017"
    depends_on:
      - etendermongodb
    ports:
      - "8000:80"
      
### Sourcing Service ###
  etender.sourcing:
    container_name: etendersourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://etendermongodb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - etendermongodb
      - rabbitmq
    ports:
      - "8001:80"